[project]
name = "jtext"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.10.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
]
